// ─────────────────────────────────────────────────────────────────────────────
//  Phase 12 — BIS Terminology Dictionary
// ─────────────────────────────────────────────────────────────────────────────

import type { TerminologyEntry } from '../types/i18n.js';

export const BIS_TERMINOLOGY_DICTIONARY: Record<string, TerminologyEntry> = {
  BIS: {
    key: 'BIS',
    en: 'Bureau of Indian Standards',
    ta: 'இந்திய தர நிர்ணய பணியகம் (BIS)',
    hi: 'भारतीय मानक ब्यूरो (BIS)',
    description: 'National Standards Body of India established under the BIS Act 2016.',
    preserveCanonicalTerm: true,
    category: 'ORGANIZATION',
  },
  INDIAN_STANDARD: {
    key: 'INDIAN_STANDARD',
    en: 'Indian Standard',
    ta: 'இந்திய தரநிலை (Indian Standard)',
    hi: 'भारतीय मानक (Indian Standard)',
    description: 'National standard published by BIS, prefixed with "IS".',
    preserveCanonicalTerm: false,
    category: 'REGULATORY',
  },
  ISI_MARK: {
    key: 'ISI_MARK',
    en: 'ISI Mark',
    ta: 'ஐஎஸ்ஐ முத்திரை (ISI Mark)',
    hi: 'आईएसआई मार्क (ISI Mark)',
    description: 'Conformity mark for industrial products under BIS Scheme-I.',
    preserveCanonicalTerm: true,
    category: 'CERTIFICATION',
  },
  CML: {
    key: 'CML',
    en: 'Certification Marks Licence (CM/L)',
    ta: 'சான்றிதழ் முத்திரை உரிமம் (CM/L)',
    hi: 'प्रमाणन चिह्न लाइसेंस (CM/L)',
    description: 'Unique 7 or 8 digit licence number granted to manufacturers under Scheme-I.',
    preserveCanonicalTerm: true,
    category: 'CERTIFICATION',
  },
  CRS: {
    key: 'CRS',
    en: 'Compulsory Registration Scheme (CRS)',
    ta: 'கட்டாய பதிவு திட்டம் (CRS)',
    hi: 'अनिवार्य पंजीकरण योजना (CRS)',
    description: 'Self-declaration conformity scheme (Scheme-II) for electronic/IT goods.',
    preserveCanonicalTerm: true,
    category: 'CERTIFICATION',
  },
  QCO: {
    key: 'QCO',
    en: 'Quality Control Order (QCO)',
    ta: 'தரக் கட்டுப்பாட்டு உத்தரவு (QCO)',
    hi: 'गुणवत्ता नियंत्रण आदेश (QCO)',
    description: 'Statutory order issued by Indian ministries making BIS certification mandatory.',
    preserveCanonicalTerm: true,
    category: 'REGULATORY',
  },
  HUID: {
    key: 'HUID',
    en: 'Hallmark Unique Identification (HUID)',
    ta: 'தனித்துவ ஹால்மார்க் அடையாள எண் (HUID)',
    hi: 'हॉलमार्क विशिष्ट पहचान संख्या (HUID)',
    description: '6-digit laser-engraved alphanumeric code for precious metal jewellery.',
    preserveCanonicalTerm: true,
    category: 'HALLMARKING',
  },
  AHC: {
    key: 'AHC',
    en: 'Assaying & Hallmarking Centre (AHC)',
    ta: 'உலோக மதிப்பீடு மற்றும் ஹால்மார்க்கிங் மையம் (AHC)',
    hi: 'परख एवं हॉलमार्किंग केंद्र (AHC)',
    description: 'BIS-recognized testing centre for hallmarking gold and silver articles.',
    preserveCanonicalTerm: true,
    category: 'HALLMARKING',
  },
  NABL: {
    key: 'NABL',
    en: 'National Accreditation Board for Testing and Calibration Laboratories (NABL)',
    ta: 'சோதனை மற்றும் அளவுத்திருத்த ஆய்வகங்களின் தேசிய அங்கீகார வாரியம் (NABL)',
    hi: 'परीक्षण और अंशांकन प्रयोगशालाओं के लिए राष्ट्रीय प्रत्यायन बोर्ड (NABL)',
    description: 'Autonomous accreditation body under the Department for Promotion of Industry and Internal Trade.',
    preserveCanonicalTerm: true,
    category: 'TESTING',
  },
  STI: {
    key: 'STI',
    en: 'Scheme of Testing and Inspection (STI)',
    ta: 'சோதனை மற்றும் ஆய்வுத் திட்டம் (STI)',
    hi: 'परीक्षण और निरीक्षण योजना (STI)',
    description: 'Mandatory quality surveillance and factory testing schedule prescribed by BIS.',
    preserveCanonicalTerm: true,
    category: 'TESTING',
  },
  SCHEME: {
    key: 'SCHEME',
    en: 'Conformity Assessment Scheme',
    ta: 'இணக்க மதிப்பீட்டுத் திட்டம்',
    hi: 'अनुरूपता मूल्यांकन योजना',
    description: 'Standardized assessment mechanism defined under BIS (Conformity Assessment) Regulations 2018.',
    preserveCanonicalTerm: false,
    category: 'CERTIFICATION',
  },
  LICENCE: {
    key: 'LICENCE',
    en: 'BIS Licence',
    ta: 'BIS உரிமம்',
    hi: 'बीआईएस लाइसेंस',
    description: 'Official authorization granted by BIS to apply the Standard Mark.',
    preserveCanonicalTerm: false,
    category: 'CERTIFICATION',
  },
  HALLMARK: {
    key: 'HALLMARK',
    en: 'Hallmark',
    ta: 'ஹால்மார்க் (Hallmark)',
    hi: 'हॉलमार्क (Hallmark)',
    description: 'Official mark stamped on precious metal articles certifying purity.',
    preserveCanonicalTerm: false,
    category: 'HALLMARKING',
  },
  PRODUCT_MANUAL: {
    key: 'PRODUCT_MANUAL',
    en: 'Product Manual',
    ta: 'தயாரிப்பு கையேடு (Product Manual)',
    hi: 'उत्पाद मैनुअल (Product Manual)',
    description: 'Guideline document published by BIS describing sampling, testing, and grouping guidelines.',
    preserveCanonicalTerm: false,
    category: 'REGULATORY',
  },
  TEST_REPORT: {
    key: 'TEST_REPORT',
    en: 'Test Report',
    ta: 'சோதனை அறிக்கை (Test Report)',
    hi: 'परीक्षण रिपोर्ट (Test Report)',
    description: 'Formal report issued by an accredited laboratory documenting sample test results.',
    preserveCanonicalTerm: false,
    category: 'TESTING',
  },
  COMPLIANCE: {
    key: 'COMPLIANCE',
    en: 'Compliance & Conformity',
    ta: 'தர இணக்கம் (Compliance)',
    hi: 'मानक अनुपालन (Compliance)',
    description: 'Fulfillment of all specified requirements of Indian Standards and regulations.',
    preserveCanonicalTerm: false,
    category: 'REGULATORY',
  },
};
